# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Remind Outdated'
description: 'A GitHub Action uses PR or issue to remind you that your reference GitHub Actions has outdated.'
author: 'xrkffgg'

branding:
  # https://feathericons.com/
  # e.g. https://haya14busa.github.io/github-action-brandings/
  icon: 'file'
  color: 'blue'

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true

#outputs:
#  result:
#    description: action result

runs:
  using: 'node12'
  main: 'dist/index.js'
